config/routes.rb
Rails.application.routes.draw do
  root "friends#index"
  resources :friends
  # get 'friends', to: "friends#index"
  # get 'friends/:id', to: "friends#show"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/friend.rb
class Friend < ApplicationRecord
    validates :fname, presence: true
    validates :lname, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/friends_controller.rb
class FriendsController < ApplicationController
  before_action :set_friend, only: [:show, :edit, :update, :destroy]

  def index
    @friends = Friend.all
  end

  def new
    @friend = Friend.new
  end

  def create
    @friend = Friend.new(friend_params)
    if @friend.save
      flash[:notice] = "Friend detail saved!"
      redirect_to @friend
    else
      render 'new'
    end
  end

  def show
  end

  def edit
  end

  def update
    if @friend.update(friend_params)
      flash[:notice] = "Friend detail updated successfully!"
      redirect_to @friend
    else
      render 'edit'
    end
  end

  def destroy
    @friend.destroy
    redirect_to friends_path
  end

  private
  def set_friend
    @friend = Friend.find(params[:id])
  end

  def friend_params
    params.require(:friend).permit(:fname, :lname)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/friends_helper.rb
module FriendsHelper
end

app/views/friends/_form.html.erb
<% if @friend.errors.any? %>
    <h3>Resolve the following errors to save</h3>
    <ul>
        <% @friend.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
        <% end %>
    </ul>
<% end %>

<%= form_with(model: @friend, local: true) do |f| %>
    <p>
        <%= f.label :fname %></br>
        <%= f.text_field :fname %>
    </p>

    <p>
        <%=  f.label :lname %></br>
        <%= f.text_field :lname %>
    </p>

    <p>
        <%= f.submit %>
    </p>
<% end %>

app/views/friends/edit.html.erb
<h1>Edit friend</h1>

<%= render 'form' %>

<h4><%= link_to "Back", friends_path %></h4>

app/views/friends/index.html.erb
<h1>List of all Friends</h1>
<table>
    <tr>
        <th>First Name</th>
        <th>Last Name</th>
        <th colspan=3>Action</th>
    </tr>
    <% @friends.each do |friend| %>      
        <tr>
            <td><%= friend.fname %></td>
            <td><%= friend.lname %></td>
            <td><%= link_to "Show", friend_path(friend) %></td>
            <td><%= link_to "Edit", edit_friend_path(friend) %></td>
            <td><%= link_to "Destroy", friend_path(friend), method: :delete, data: { confirm: 'Are you sure?'}  %></td>
        </tr>
    <% end %>
    <h3>Add new friend, <%= link_to "New friend", new_friend_path %></h3>
</table>

app/views/friends/new.html.erb
<h1>Add new friend</h1>

<%= render 'form' %>

<h4><%= link_to "Back", friends_path %></h4>

app/views/friends/show.html.erb
<h1>Friend details</h1>
<%= "hey #{@friend.fname}" %></br>
<%= link_to "Edit", edit_friend_path(@friend) %> |
<%= link_to "Delete", friend_path(@friend), method: :delete, data: { confirm: 'Are you sure?'} %> |
<%= link_to "Home page", friends_path %>

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
    <%= msg %>
<% end %>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
      <a class="navbar-brand" id ="logo" href="#">Friends</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item active">
            <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">Link</a>
          </li>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              Dropdown
            </a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
              <a class="dropdown-item" href="#">Action</a>
              <a class="dropdown-item" href="#">Another action</a>
              <div class="dropdown-divider"></div>
              <a class="dropdown-item" href="#">Something else here</a>
            </div>
          </li>
          <li class="nav-item">
            <a class="nav-link disabled" href="#">Disabled</a>
          </li>
        </ul>
        <form class="form-inline my-2 my-lg-0">
          <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
          <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
        </form>
      </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>HeyYou</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/navigation' %>
    <div class="container-fluid" id="home-container">
      <div class="jumbotron text-center text-white">
        <h1 class="display-4">Hiee! I am a filler :)</h1>
        <p class="lead">This is a rails applicationw using bootstrap 4.4.1</p>
        <hr class="my-4">
        <p>It uses utility classes for typography and spacing to space content out within the larger container.</p>
        <a class="btn btn-primary btn-lg" href="#" role="button">Learn more</a>
      </div>
    </div>
    <%= render 'layouts/messages' %>
    <div class="container-fluid">
      <%= yield %>
    </div>
  </body>
</html>